!include d:\toolkit\c\samples\toolkit.inc
.SUFFIXES: .cpp .c
.cpp.obj:
	wpp386 -ox -DNDEBUG $*.cpp
.c.obj:
	wcc386 -ox -DNDEBUG $*.c

all:	copydate.exe .symbolic

copydate.exe:	copydate.obj copydate.lnk
	$(LINK) $(LFLAGS) @copydate.lnk

copydate.obj:	copydate.cpp

